name: RiskGuard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Backend
    - name: Use Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install Backend Deps
      working-directory: ./risk-backend
      run: npm install

    - name: Run Backend Tests
      working-directory: ./risk-backend
      run: npm test

    # Frontend
    - name: Use Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Frontend Deps
      working-directory: ./risk-frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./risk-frontend
      run: npm run build
